image: maven:3.9.4-eclipse-temurin-21-alpine

stages:
  - build
  - verify

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

before_script:
  - echo "Using Java:"
  - java -version
  - mvn -version

build:
  stage: build
  script:
    - mvn clean compile

verify:
  stage: verify
  script:
    - java -version
    - mvn verify

  artifacts:
    when: always
    paths:
      - target
